<?php

use Shared\Model\Domain\User\Role;
use Shared\Model\Infrastructure\Authentication\Identity;

?>
<?= $this->doctype() ?>
<html lang="fr">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

        <?php
        if (! empty($this->metaTitle)) {
            $this->plugin('headTitle')->prepend($this->metaTitle);
        }
        ?>

        <?= $this->headTitle(), $this->headMeta(), $this->headLink(); ?>

        <?php if (! empty($this->metaDescription)) : ?>
            <meta name="description" content="<?= $this->escapeHtml($this->metaDescription); ?>"/>
        <?php endif; ?>
    </head>
<body>

<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="<?= $this->url('application') ?>">Blog</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar" aria-controls="navbar" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbar">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="<?= $this->url('application') ?>">Home</a>
                </li>
            </ul>
            <ul class="navbar-nav">
                <?php if ($this->layout()->identity instanceof Identity): ?>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Menu
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <?php if ($this->layout()->identity->getRoleId() === Role::ADMINISTRATOR): ?>
                                <a class="dropdown-item" href="<?= $this->url('admin'); ?>">Administration</a>
                            <?php endif; ?>
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" href="<?= $this->url('logout'); ?>">Déconnexion</a>
                        </div>
                    </li>
                <?php endif; ?>
            </ul>
        </div>
    </div>
</nav>

<div class="container">
    <?= $this->content ?>
</div>

<?= $this->headScript(); ?>

<script type="text/javascript">
    $(document).ready(function() {
        application.init();
    });
</script>


<?= $this->inlineScript() ?>

</body>
</html>
