<?php if ($this->pageCount): ?>
    <nav>
        <ul class="pagination">
            <?php if (isset($this->previous)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, ['page' => $this->previous]); ?>">Previous</a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <span class="page-link">Previous</span>
                </li>
            <?php endif; ?>

            <?php foreach ($this->pagesInRange as $page): ?>
                <?php if ($page != $this->current): ?>
                    <li class="page-item"><a class="page-link" href="<?= $this->url($this->route, ['page' => $page]); ?>"><?= $page; ?></a></li>
                 <?php else: ?>
                    <li class="page-item active">
                        <span class="page-link">
                            <?= $page; ?>
                        <span class="sr-only">(current)</span>
                    </span>
                <?php endif; ?>
            <?php endforeach; ?>

            <?php if (isset($this->next)): ?>
                <li class="page-item">
                    <a class="page-link" href="<?= $this->url($this->route, ['page' => $this->next]); ?>">Next</a>
                </li>
            <?php else: ?>
                <li class="page-item disabled">
                    <span class="page-link">Next</span>
                </li>
            <?php endif; ?>
        </ul>
    </nav>
<?php endif; ?>